A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('post.urls', namespace='post')),
    path('api/', include('api.urls', namespace='api')),
    
    
    
]

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signin/', views.SignInView.as_view(), name='login'),
    # path('signin/mobile/', views.SignInMobileView.as_view(), name='login_mobile'),
    path('signup/', views.UserSignupView.as_view(), name='logup'),
    path('verify/', views.VerifyUserView.as_view(), name='verify_code'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='profile'),
    # path('profile/<int:user_id>/<str:slug_id>/', views.UserProfileView.as_view(), name='profile_post'),
    path('reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.PasswordResetComplateView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),
    path('edit/<int:user_id>/', views.EditProfileView.as_view(), name='edit_profile'),
    path('notification/', views.NotifictionView.as_view(), name='notification_user'),
    
    
    
    
]

api/urls.py
from django.urls import path
from api.views.accounts import SignUpApiView, ProfileApiView
from api.views.comments import *
from api.views.home import HomeView
from rest_framework.authtoken import views as auth_views
from api.views.posts import *


app_name = 'api'
urlpatterns = [
    path('signup/', SignUpApiView.as_view(), name='signup_api'),
    path('profile/<int:user_id>/', ProfileApiView.as_view(), name='profile'),
    path('auth-token/', auth_views.obtain_auth_token, name='auth_token'),
    path('home/', HomeView.as_view(), name='home'),
    path('create-posts/', PostCreateApiView.as_view(), name='post_create'),
    path('show-posts/', PostGetApiView.as_view(), name='show-post'),
    path('update-posts/<int:post_id>/', PostUpdateApiView.as_view(), name='update-post'),
    path('delete-posts/<int:post_id>/', PostDeleteApiview.as_view(), name='update-post'),
    path('create-comments/', CommentsCreateApiView.as_view(), name='comment_create_api'),
    path('show-comments/', CommetsGetApiView.as_view(), name='comment_create_api'),
    path('update-comments/<int:comment_id>/', CommetsUpdateApiView.as_view(), name='update_comments'),
    path('delete-comments/<int:comment_id>/', CommetsDeleteApiView.as_view(), name='delete-comments'),
    
    
    
]

accounts/models.py
from django.urls import reverse
from django.utils import  timezone
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import AbstractBaseUser, AbstractUser
from .managers import MyManager
from core.models import CreateModel, UpdateModel, DeleteModel


class User(AbstractBaseUser, CreateModel, UpdateModel):
    username = models.CharField(_("Username"), max_length=100, unique=True)
    email = models.EmailField(_("Email"), max_length=255, unique=True)
    full_name = models.CharField(_("Full name"), max_length=255)
    mobile_phone = models.CharField(_("Mobile"), max_length=11, unique=True)
    birthday = models.DateField(_("Birth day"), default=timezone.now)
    is_admin = models.BooleanField(_("is admin"), default=False)
    is_active = models.BooleanField(_("is active"), default=True)
    is_superuser = models.BooleanField(_("is superuser"), default=False)
    
    gender = (
        ('1', 'male'),
        ('2', 'female'),
    )
    gender_choose = models.CharField(_("Gender"), max_length=1, choices=gender)
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ('full_name', )
    
    objects = MyManager()
    
    def has_perm(self, perm, obj=None):
        # if self.is_active and self.is_superuser:
            return True
    
    def has_module_perms(self, app_labe):
        # if self.is_active and self.is_superuser:
            return True
        
    def get_absolute_url(self):
        return reverse('accounts:profile', args=(self.id))
    
    @property
    def is_staff(self):
        return self.is_admin
    
    def __str__(self) :
        return self.username
    
    def get_absolute_url(self):
        return reverse("model_detail", kwargs={"pk": self.pk})
    
    def delete(self, using=None, keep_parents=False):
        self.is_deleted = True
        self.deleted_at = timezone.now()
        self.save()
    
    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")
        db_table = "users-model"
        
        
class Imageuser(CreateModel):
    user = models.OneToOneField(User, on_delete=models.PROTECT)
    image = models.ImageField(upload_to='profile')
    
    class Meta:
        verbose_name = _('image user')
        verbose_name_plural = _('image users')
        db_table = 'image_user_model'
        
class RecycleUser(User):
    deleted = MyManager()
    class Meta:
        proxy = True


class RelationUserModel(CreateModel):
    from_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='followers')
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='following')
    
    class Meta:
        verbose_name = _('relation')
        verbose_name_plural = _('relations')
        db_table = 'relation-model'
    def __str__(self) -> str:
        return f'{self.from_user}  {self.to_user}'


class NotificationModel(CreateModel):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='Unotification')
    body = models.TextField(_('body notification'))
    
    class Meta:
        verbose_name = _('notification-model')
        verbose_name_plural = _('notifications-models')
        db_table = 'notofication-model'
        

class OtpCode(CreateModel):
    # user = models.ForeignKey(User, on_delete=models.CASCADE)
    email = models.EmailField(unique=True)
    # mobile_phone = models.CharField(_('mobile'), max_length=11, unique=True, blank=True)
    active_code = models.PositiveIntegerField()
    
    def __str__(self):
        return f'{self.email} -- {self.active_code}'
    
    class Meta:
        verbose_name = _('otp-code')
        verbose_name_plural = _('otp-codes')
        db_table = 'otp-code-model'

accounts/views.py
from typing import Any
from django import http
from django.shortcuts import render, redirect, get_object_or_404, get_list_or_404
from .models import User, RelationUserModel, NotificationModel, OtpCode
from .form import UserCreationForms, UserChangeForms, UserSignIn, UserSignUpForm, UserEditProfileForm, VerifyCodeForm
from django.views import View
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm, PasswordResetForm 
from django.contrib.auth.mixins import LoginRequiredMixin
from post.models import PostModel
from django.contrib.auth import views as auth_views
from django.urls import reverse, reverse_lazy
import random
from utils import send_otp_code

class UserSignupView(View):
    form_class = UserSignUpForm
    template_name = 'accounts/singup.html'
    
    def get(self, reques):
        form = self.form_class()
        return render(reques, self.template_name, {'form': form})
    
    def post(self,requests):
        form = self.form_class(requests.POST)
        if form.is_valid():
            cd = form.cleaned_data
            random_code = random.randint(1000, 999999)
            send_otp_code(cd['email'], random_code)
            OtpCode.objects.create(email=cd['email'], active_code=random_code)
            requests.session['User_register_info'] = {
                'email' : cd['email'],
                'full_name': cd['full_name'],
                'password': cd['password'],
            }
            # messages.success(requests, 'successfully create account', 'success')
            return redirect('accounts:verify_code')
        return render(requests, self.template_name, {'form': form})


class VerifyUserView(View):
    form_class = VerifyCodeForm
    template_name = 'accounts/verify_code.html'
    
    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})
        
    def post(self, request):
        user_session = request.session['User_register_info']
        code_instance = OtpCode.objects.get(email=user_session['email'])
        form = self.form_class()
        if form.is_valid():
            cd = form.cleaned_data
            if cd['code'] == code_instance.code:
                User.objects.create_user(
                    user_session['email'],
                    user_session['full_name'],
                    user_session['password']
                )
                code_instance.delete()
                messages.success(request, 'successfully create account', 'success')
                return redirect('post:home')
        messages.error(request, 'wrong code', 'warning')
        return redirect('accounts:verify_code')
            
            
class SignInView(View):

    def setup(self, request, *args, **kwargs):
        self.next = request.GET.get('next', None)
        return super().setup(request, *args, **kwargs)
    
    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('post:home')
        return super().dispatch(request, *args, **kwargs)
    
    form_class = UserSignIn
    template_name = 'accounts/signin.html'
    
    def get(self, request):
        signin = self.form_class()
        context = {
            'form': signin
        }
        return render(request, self.template_name, context)
    
    def post(self, request):
        signin = self.form_class(request.POST)
        if signin.is_valid():
            cd = signin.cleaned_data
            user = authenticate(
                username=cd['username'],
                password=cd['password']
            )
            
            if user is not None:
                login(request, user)
                messages.success(request, 'Login successful', 'success')
                if self.next:
                    return redirect(self.next)
                return redirect('post:home')
            messages.error(request, 'username or password is wrong', 'warning')
        return render(request, self.template_name, {'form': signin})
        
class LogOutView(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        messages.success(request, 'Logged out successfully', 'success')
        return redirect('accounts:login')
    
    
class UserProfileView(LoginRequiredMixin,View):
    def get(self, request, user_id):
        is_following = False
        user = User.objects.get(pk=user_id)
        post = PostModel.objects.all()
        relation = RelationUserModel.objects.filter(from_user=request.user, to_user=user.id)
        if relation.exists():
            is_following = True
        context = {
            'user': user,
            'post': post,
            'is_following': is_following
            
            
        }
        return render(request, 'accounts/profile.html', context)
    
    
class EditProfileView(LoginRequiredMixin, View):
    
    def setup(self, request, *args, **kwargs):
        self.user = get_object_or_404(User, pk=kwargs['user_id'])
        return super().setup(request, *args, **kwargs)
    
    def dispatch(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs['user_id'])
        if request.user.id != user.id:
            messages.error(request, 'invalid', 'danger')
            return redirect('post:home')
        return super().dispatch(request, *args, **kwargs)
    
    template_name = 'accounts/edit-profile.html'
    from_class = UserEditProfileForm
    
    def get(self, request, *args, **kwargs):
        user = self.user
        update_user = self.from_class(instance=user)
        return render(request, self.template_name, {'user': update_user})
        
    def post(self, request, *args, **kwargs):
        user = self.user
        update_user = self.from_class(request.POST, instance=user)
        if update_user.is_valid():
            update_user.save()
            messages.success(request, 'successfly edit profile', 'success')
            return redirect('accounts:profile', request.user.id)
        return render(request, self.template_name, {'user': update_user})
        

# show form reset password and send form reset password to email account
class UserPasswordResetView(auth_views.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    
    # redirect to who is page
    success_url = reverse_lazy('accounts:password_reset_done')
    
    # send content to email user
    email_template_name = 'accounts/password_reset_email.html'
    

# show success send email
class UserPasswordResetDoneView(auth_views.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'
    

# show fileds password
class UserPasswordResetConfirmView(auth_views.PasswordResetConfirmView):
    # show form to user
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')
    
    
# show message after password reset
class PasswordResetComplateView(auth_views.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'
    

class UserFollowView(LoginRequiredMixin, View):
    # template_name = 'accounts/follow.html'
    
    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs['user_id'])
        relation = RelationUserModel.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            messages.error(request, 'you follow this user', 'warning')
        else:
            RelationUserModel.objects.create(from_user=request.user, to_user=user)
            messages.success(request, 'follow', 'success')
        return redirect('accounts:profile', user.id)
        # return render(request, self.template_name, {'from_user': user, 'to_user': relation})
    
    
class UserUnfollowView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs['user_id'])
        relation = RelationUserModel.objects.filter(from_user=request.user, to_user=user)
        if relation.exists():
            relation.delete()
            messages.success(request, 'unfollow', 'success')
        return redirect('accounts:profile', user.id)
    

class NotifictionView(View):
    def get(self, request):
        notification = NotificationModel.objects.all()
        return render(request, 'accounts/notification.html', {'notification': notification})
        

api/views/accounts.py
from rest_framework.response import Response
from api.serializers.account import SignupSerializers, ProfileSerializers
from rest_framework.views import APIView
from accounts.models import User
from rest_framework import status
from django.contrib.auth import authenticate, login
from rest_framework.permissions import IsAuthenticated


class SignUpApiView(APIView):
    def post(self, request):
        ser_data = SignupSerializers(data=request.data)
        if ser_data.is_valid():
            User.objects.create_user(
                full_name = ser_data._validated_data['full_name'],
                username = ser_data._validated_data['username'],
                email = ser_data._validated_data['email'],
                mobile_phone = ser_data.validated_data['mobile_phone'],
                password= ser_data.validated_data['password'],)
            return Response(ser_data.data, status=status.HTTP_201_CREATED)
        return Response(ser_data.errors, status=status.HTTP_400_BAD_REQUEST)
    

class ProfileApiView(APIView):
    permission_classes = (IsAuthenticated,)
    
    def get(self, request, user_id):
        user = User.objects.get(pk=user_id)
        ser_data = ProfileSerializers(instance=user)
        return Response(ser_data.data, status=status.HTTP_200_OK)


class FollowUserApiView(APIView):
    def get(self, request):
        ...
        

class UnfollowUserApiView(APIView):
    def get(self, request):
        ...
        

accounts/templates/accounts/edit-profile.html
{% extends 'base.html' %}

{% block title %}
    <title>edit user</title>
{% endblock  %}

{% block content %}
    <section>
        <form method='POST' action=''>
            {% csrf_token %}
            {{ user }}
            <input type='submit' value='edit profile' class='btn btn-primary'>
        </form>
    </section>
{% endblock  %}

accounts/templates/accounts/follow.html
{% extends 'base.html' %}

{% block title %}
    <title>follow</title>
{% endblock  %}

{% block content %}
    {{ from_user }} </br>
    {{ to_user }}
{% endblock  %}

accounts/templates/accounts/notification.html
{% extends "base.html" %}


{% block title %}
    <title>notification</title>
{% endblock title %}


{% block content %}
    <section>
        {% for notifications in notification %}
        {% if notifications.user.id == request.user.id %}
            <div class='card'>
                <h6 class='card-header'>{{ notifications.user }}</h6>
                <p class='card-body'>
                    {{ notifications.body }} </br> date: {{ notifications.create_at }}
                </p>
            </div>
        {% endif %}
    </section>
        {% endfor %}
{% endblock content %}
    
    

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}

{% block title %}
    <title>complete password</title>
{% endblock  %}

{% block content %}
    <p>you success password reset</p>
{% endblock  %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}

{% block title %}
    <title>confirm password</title>
{% endblock  %}

{% block content %}
    {% if validlink %}
        <form method='post' action='' class='tezt center'>
            {% csrf_token %}
            {{ form }}
            <input type='submit' value='change done'>
        </form>
        {% else %}
            <p>this ink expired you can tray again</p>
    {% endif %}
{% endblock  %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}

{% block title %}
    <title>password done</title>
{% endblock  %}

{% block content %}
    <p>we send link recovery password to email</p>
{% endblock  %}

accounts/templates/accounts/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow the link below:
{{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}

{% block title %}
    <title>password reset</title>
{% endblock  %}

{% block content %}
    <form method='post' action='' class='text-center' novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <a href='#' class=''>user instance mobile phone</a> </br> </br>
        <input type='submit' value='send email' class='btn btn-primary'>

    </form>
{% endblock  %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block title %}
    <title>profile</title>
{% endblock  %}

{% block content %}
    full_name: {{ user.full_name }} </br>
    username {{ user.username }} </br>
    email: {{ user.email }} </br>
    mobbile phone: {{ user.mobile_phone }} </br></br>

    <a href='{% url "accounts:edit_profile" request.user.id %}' class='btn btn-info'>edit profile</a>


    {% if request.user.id != user.id and not is_following %}
        <a class='btn btn-primary' href='{% url "accounts:user_follow" user.id %}' >follow</a>
    
    {% elif request.user.id != user.id and is_following%}
        <a class='btn btn-primary' href='{% url "accounts:user_unfollow" user.id %}' >unfollow</a>

    {% endif %}
</br>
    
    <span>all post {{ post.count }}</span>





{% endblock  %} 

accounts/templates/accounts/signin.html
{% extends 'base.html' %}

{% load static %}

{% block load_refrences %}
  <link rel='stylesheet' href='{% static "css/login.css" %}'>
{% endblock  %}

{% block title %}
    <title>sign in</title>
{% endblock  %}

{% block content %}
    <section class='section-login'>
        <form action='' method='post' novalidate class='m-2'>
            {% csrf_token %}
            {{ form }}
            <input type='submit' value='login' class='btn-login btn btn-primary'>
        </form> 

          <nav aria-label="breadcrumb">
            <ol class="breadcrumb justify-content-center">
              <li class="breadcrumb-item"><a href="{% url "accounts:password_reset" %}">forget password</a></li>
              <li class="breadcrumb-item"><a href="{% url "accounts:logup" %}">create account</a></li>
              <li class="breadcrumb-item"><a href="{% url "post:home" %}">Home</a></li>
            </ol>
          </nav>
    </section>
{% endblock  %}

accounts/templates/accounts/signin_mobile.html
{% extends 'base.html' %}

{% block title %}
    <title>sginin</title>
{% endblock  %}

{% block content %}
    <form method='post' action=''>
        {% csrf_token %}
        {{ signin }}
    </form>
{% endblock  %}

accounts/templates/accounts/singup.html
{% extends 'base.html' %}

{% block title %}
    <title>logup</title>
{% endblock  %}

{% block content %}
    <form method='post' action='' novalidate class='col-md-6'>
        {% csrf_token %}
        {{ form.errors }}
        {{ form }}
        <input type='submit' value='create account' class='btn btn-primary'>
    </form>
    <a href='#' class=''>user intance mobile phone</a> </br>
    <a href='{% url "accounts:login" %}'>login account</a>
{% endblock  %}

accounts/templates/accounts/verify_code.html
{% extends 'base.html' %}

{% block title %}
    <title>active</title>
{% endblock  %}


{% block content %}
    <form action='' method='post'>
        {% csrf_token %}
        {{ form }}
        <input type='submit' value='accept account' class='btn btn-primary'>
    </form>
{% endblock content %}
    