A/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('', include('post.urls', namespace='post')),
    path('api/', include('api.urls', namespace='api')),
    
    
    
]

accounts/urls.py
from django.urls import path
from . import views


app_name = 'accounts'
urlpatterns = [
    path('signin/', views.SignInView.as_view(), name='login'),
    # path('signin/mobile/', views.SignInMobileView.as_view(), name='login_mobile'),
    path('signup/', views.UserSignupView.as_view(), name='logup'),
    path('verify/', views.VerifyUserView.as_view(), name='verify_code'),
    path('logout/', views.LogOutView.as_view(), name='logout'),
    path('profile/<int:user_id>/', views.UserProfileView.as_view(), name='profile'),
    # path('profile/<int:user_id>/<str:slug_id>/', views.UserProfileView.as_view(), name='profile_post'),
    path('reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.PasswordResetComplateView.as_view(), name='password_reset_complete'),
    path('follow/<int:user_id>/', views.UserFollowView.as_view(), name='user_follow'),
    path('unfollow/<int:user_id>/', views.UserUnfollowView.as_view(), name='user_unfollow'),
    path('edit/<int:user_id>/', views.EditProfileView.as_view(), name='edit_profile'),
    path('notification/', views.NotifictionView.as_view(), name='notification_user'),
    
    
    
    
]

api/urls.py
from django.urls import path
from api.views.accounts import SignUpApiView, ProfileApiView
from api.views.comments import *
from api.views.home import HomeView
from rest_framework.authtoken import views as auth_views
from api.views.posts import *


app_name = 'api'
urlpatterns = [
    path('signup/', SignUpApiView.as_view(), name='signup_api'),
    path('profile/<int:user_id>/', ProfileApiView.as_view(), name='profile'),
    path('auth-token/', auth_views.obtain_auth_token, name='auth_token'),
    path('home/', HomeView.as_view(), name='home'),
    path('create-posts/', PostCreateApiView.as_view(), name='post_create'),
    path('show-posts/', PostGetApiView.as_view(), name='show-post'),
    path('update-posts/<int:post_id>/', PostUpdateApiView.as_view(), name='update-post'),
    path('delete-posts/<int:post_id>/', PostDeleteApiview.as_view(), name='update-post'),
    path('create-comments/', CommentsCreateApiView.as_view(), name='comment_create_api'),
    path('show-comments/', CommetsGetApiView.as_view(), name='comment_create_api'),
    path('update-comments/<int:comment_id>/', CommetsUpdateApiView.as_view(), name='update_comments'),
    path('delete-comments/<int:comment_id>/', CommetsDeleteApiView.as_view(), name='delete-comments'),
    
    
    
]

templates/components/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{msg.tags}}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/components/navbar.html
<nav class="navbar navbar-expand-lg bg-dark navbar-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'post:home' %}">Sciol</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url "post:home" %}">Home</a>
          </li>
          <li class="nav-item">

            {% if request.user.is_authenticated %}
                <li class='dropdown-item'>
                  <a class='nav-link' href='{% url "accounts:profile" request.user.id %}'>login {{ user.full_name }}</a>
                </li>
            {% endif %}
            
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              account
            </a>
            <ul class="dropdown-menu">
                {% if request.user.is_authenticated %}
                    <li><a class="dropdown-item" href="{% url "accounts:logout" %}">signout</a></li>
                {% else %}
                    <li><a class="dropdown-item" href="{% url "accounts:logup" %}">sginup</a></li>
                    <li><a class="dropdown-item" href="{% url 'accounts:login' %}">sginin</a></li>
                {% endif %}
            </ul>
          </li>
          <li class="nav-item">
            <a class="nav-link" href='{% url "accounts:notification_user" %}'>notification</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="search">Search</button>
        </form>
      </div>
    </div>
  </nav>